version: 1
formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(module)s - %(message)s'
    human:
        format: '[%(levelname)s] %(module)s: %(message)s'
    line:
        format: '--------------------------------------------------------------------------------'
handlers:
    console:
        class: logging.StreamHandler
        level: WARNING
        formatter: human
        stream: ext://sys.stderr
    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: retrieve.log
    headline:
        class: logging.FileHandler
        level: INFO
        formatter: line
        filename: retrieve.log
loggers:
    headline:
        level: INFO
        handlers: [headline]
root:
  level: DEBUG
  handlers: [console, file]
